### ISSUE TITLE
Build under 64-Bit windows

### ISSUE THREAD

**Issue by uhagi** [geggo/MVacquire#3]
Hi

Did you try to build  and run under 64-Bit windows ?
Here the mv.pyd crahes python after loading...

**Comment by sriramyab** [comment]
Hello, I am trying to establish serial communication between camera and my linux laptop. I used your instructions to setup stuff. I am not able to execute the program correctly. I am using a bluefox MLC"
Is there an easier way to establish the serial communication between camera and linux? 

Do you have any idea whats going wrong? Any help is appreciated. 

**After plugging in the camera when i run my python file for the first time:**
    for name in root.Devices.children:
  File "_mvDeviceManager.pyx", line 590, in mv.List.children.__get__ (_mvDeviceManager.c:8448)
    return [child.name for child in self]
  File "_mvDeviceManager.pyx", line 613, in __iter__ (_mvDeviceManager.c:8855)
    yield create_component(obj)
  File "_mvDeviceManager.pyx", line 876, in mv.create_component (_mvDeviceManager.c:14321)
    obj_errcheck(OBJ_CheckHandle(obj, hcmFull)) #necessary?
  File "_mvDeviceManager.pyx", line 31, in mv.obj_errcheck (_mvDeviceManager.c:2968)
    raise MVError, DMR_ErrorCodeToString(result)
mv.MVError: PROPHANDLING_COMPONENT_ID_INVALID

** **When I run the code another time ****
Device serial=25001103 family=mvBlueFOX
1  devices found
close device 0x30000 0x0
Traceback (most recent call last):
  File "mlc.py", line 59, in <module>
    devlist = OpenDevices(namelist)
  File "mlc.py", line 34, in OpenDevices
    dev = mv.dmg.get_device(name)
  File "_mvDeviceManager.pyx", line 105, in mv.DeviceManager.get_device (_mvDeviceManager.c:3757)
    device = self.get_device_by_serial(serial)
  File "_mvDeviceManager.pyx", line 83, in mv.DeviceManager.get_device_by_serial (_mvDeviceManager.c:3579)
    return Device(hdev)
  File "_mvDeviceManager.pyx", line 160, in mv.Device.__cinit__ (_mvDeviceManager.c:4146)
    dmr_errcheck(DMR_OpenDevice(self.dev, &self.drv))
  File "_mvDeviceManager.pyx", line 25, in mv.dmr_errcheck (_mvDeviceManager.c:2874)
    raise MVError, DMR_ErrorCodeToString(result)
mv.MVError: DMR_DRV_ALREADY_IN_USE

Thanks

**Comment by geggo** [comment]
It seems things didn't go completely wrong with your setup. Please, could you try if you have success with the basic functionality as described in the tutorial section. Next, if you can narrow down your problems, open an new issue and please give details on the program you would like to run.
Gregor

**Comment by uhagi** [comment]
Hi sriramyab

This looks like the software thinks the camera is already open/in use by some other software....

>>DMR_DRV_ALREADY_IN_USE

By the way: does the camera work correctly with the standard Matrix Vision Tools like mvPropview ??

Best regards
Uwe



> Am 27.03.2016 um 15:56 schrieb sriramyab <notifications@github.com>:
> 
> DMR_DRV_ALREADY_IN_USE
